### ISSUE TITLE
search_images_ddg always fails with TimeoutError

### ISSUE THREAD

**Issue by RomanVolkov** [fastai/fastbook#528]
I've tried to use `search_images_ddg` from PaperSpace and my local environment. The result is always the same: `TimeoutError`.
I've asked the question at forum and seems I am not the only one with such problem https://forums.fast.ai/t/live-coding-2/96690/55
Looks like it got broken recently

**Comment by aspatic** [comment]
same problem on my local and colab instance of jupyter.

**Comment by jph00** [comment]
Many thanks for reporting. It appears that DDG has blocked image searches. I'll look into it -- if anyone can figure out what/how they're blocking and how to avoid it, please let us know!

**Comment by jph00** [comment]
Should be fixed now in the fastai/course22 repo and also the kaggle notebook.

**Comment by RomanVolkov** [comment]
using `ddg_images` function directly from `duckduckgo_search` package solved the problem at PaperSpace for me

**Comment by stefcon** [comment]
What's the exact fix? I've been trying to make DDG search variant work in the Jupyter version of the book, but I still get the same error.

**Comment by jph00** [comment]
It's fixed in this repo now too. The exact fix is to set the referer header to 'duckduckgo.com'
